name: Checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --locked --dev
      - name: Lint
        run: uv run ruff check
      - name: Format diff
        # Run even if previous step failed
        if: success() || failure()
        run: uv run ruff format --diff
